version: "3.9"

services:

  postgres:
    image: postgres:16

    container_name: researchanalysis-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: researchdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: .

    container_name: researchanalysis-backend

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload


volumes:
  postgres_data:
  